version: '3.1'
services:
    database:
        image: mysql:latest
        container_name: Database
        volumes:
        - ./database:/var/lib/mysql
        #- ./sql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
        - .schema.sql:/schema.sql
        ports:
        - "3307:3306"
        environment:
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        - "MYSQL_DATABASE=ProjectManager"
        - "MYSQL_INITDB_SKIP_TZINFO=yes"