version: '3.1'
services:
    database:
        image: mysql:latest
        container_name: Database
        volumes:
        - ./database:/var/lib/mysql
        ports:
        - "3307:3306"
        environment:
        - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
        - "MYSQL_USER=${MYSQL_USER}"
        - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
        - "MYSQL_DATABASE=ProjectManager"